version: "3.9"
services:
    api:
        image: adjabe/waas-api:latest
          #build:
          #  context: .
          #  # use Dockerfile.gpu when using a NVIDIA GPU
          #  dockerfile: Dockerfile
        ports:
            - "80:3000"
        volumes:
            - .:/workspace
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - DISCLAIMER
            - ALLOWED_WEBHOOKS_FILE
        command: gunicorn -w 2 -b 0.0.0.0:3000 --log-file=- 'src.main:app'
    worker:
        image: adjabe/waas-worker:latest
          #build:
          #  context: .
          #  # use Dockerfile.gpu when using a NVIDIA GPU
          #  dockerfile: Dockerfile
        volumes:
            - .:/workspace
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - ALLOWED_WEBHOOKS_FILE
        command: rq worker --url redis://redis:6379 -c worker-settings
        # Uncomment the following lines when using a NVIDIA GPU
        # deploy:
        #     resources:
        #         reservations:
        #             devices:
        #                 - driver: nvidia
        #                   capabilities: [gpu]

    redis:
        image: adjabe/redis
        ports:
            - "6379:6379"
